name: Publish package to GitHub Packages
on:
  release:
    types: [created]
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        module: [VRDR, VRCL]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Publish package
        run: mvn deploy --batch-mode -pl ${{ matrix.module }} -am clean install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
